<?php

/**
 * This is the model base class for the table "blog_comment".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "BlogComment".
 *
 * Columns in table "blog_comment" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property integer $blog_id
 * @property string $name
 * @property string $comment
 *
 */
abstract class BaseBlogComment extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'blog_comment';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'BlogComment|BlogComments', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('blog_id, name, comment', 'required'),
			array('blog_id', 'numerical', 'integerOnly'=>true),
			array('name', 'length', 'max'=>255),
			array('id, blog_id, name, comment', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'blog_id' => Yii::t('app', 'Blog'),
			'name' => Yii::t('app', 'Name'),
			'comment' => Yii::t('app', 'Comment'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('blog_id', $this->blog_id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('comment', $this->comment, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}