<?php

/**
 * This is the model base class for the table "blog".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Blog".
 *
 * Columns in table "blog" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $create_time
 * @property string $update_time
 * @property string $title
 * @property string $content
 * @property string $img
 *
 */
abstract class BaseBlog extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'blog';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Blog|Blogs', $n);
	}

	public static function representingColumn() {
		return 'title';
	}

	public function rules() {
		return array(
			array('title, content', 'required'),
			array('title, img', 'length', 'max'=>255),
			array('create_time, update_time', 'safe'),
			array('create_time, update_time, img', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, create_time, update_time, title, content, img', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'create_time' => Yii::t('app', 'Create Time'),
			'update_time' => Yii::t('app', 'Update Time'),
			'title' => Yii::t('app', 'Title'),
			'content' => Yii::t('app', 'Content'),
			'img' => Yii::t('app', 'Img'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('create_time', $this->create_time, true);
		$criteria->compare('update_time', $this->update_time, true);
		$criteria->compare('title', $this->title, true);
		$criteria->compare('content', $this->content, true);
		$criteria->compare('img', $this->img, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}