<?php

/**
 * This is the model base class for the table "advertising".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Advertising".
 *
 * Columns in table "advertising" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $title
 * @property string $lang
 * @property integer $banner_id
 * @property integer $is_active
 */
abstract class BaseAdvertising extends GxActiveRecord
{

    public static function model($className = __CLASS__)
    {
        return parent::model($className);
    }

    public function tableName()
    {
        return 'advertising';
    }

    public static function label($n = 1)
    {
        return Yii::t('app', 'Advertising|Advertisings', $n);
    }

    public static function representingColumn()
    {
        return 'title';
    }

    public function rules()
    {
        return array(
            array('banner_id,is_active', 'numerical', 'integerOnly' => true),
            array('title,category,position', 'length', 'max' => 255),
            array('lang', 'length', 'max' => 10),
            array('title, lang, banner_id,html,html_en,html_mobile, html_mobile_en', 'default', 'setOnEmpty' => true, 'value' => null),
            array('id, title, lang, banner_id, html, html_mobile,html_en,html_mobile_en,is_active', 'safe', 'on' => 'search'),
        );
    }

    public function relations()
    {
        return array();
    }

    public function pivotModels()
    {
        return array();
    }

    public function attributeLabels()
    {
        return array(

            'id' => Yii::t('app', 'ID'),
            'title' => Yii::t('app', 'Title'),
            'is_active'=>Yii::t('app', 'Is Active'),
            'html'=>Yii::t('app', 'Html RU'),
            'html_mobile'=>Yii::t('app', 'Html mobile RU'),
            'html_en'=>Yii::t('app', 'Html EN'),
            'html_mobile_en'=>Yii::t('app', 'Html mobile EN'),

            'lang' => Yii::t('app', 'Lang'),
            'banner_id' => Yii::t('app', 'Banner'),
            'category'=>'Категория',
            'position'=>'Позиция'
        );
    }

    public function search()
    {
        $criteria = new CDbCriteria;
        $criteria->compare('id', $this->id);
        $criteria->compare('is_active', $this->is_active);
        $criteria->compare('title', $this->title, true);
        $criteria->compare('lang', $this->lang, true);
        $criteria->compare('banner_id', $this->banner_id);
        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
            'pagination'=>array(
                'pageSize'=> 100
            ),
        ));
    }
}